version: "3.8"
services:
  whisper:
    image: ghcr.io/kth8/whisper-server-vulkan:latest
    container_name: whisper
    restart: always
    read_only: true
    devices:
      - /dev/kfd
      - /dev/dri
    tmpfs:
      - /root/.cache/mesa_shader_cache
    ports:
      - "8002:8080"
    labels:
      io.containers.autoupdate: "registry"
    init: true
