version: "3.8"
services:
  whisper-server-vulkan:
    image: ghcr.io/kth8/whisper-server-vulkan
    container_name: whisper-server-vulkan
    init: true
    labels:
      - "io.containers.autoupdate=registry"
    ports:
      - "8001:8080"
    devices:
      - /dev/kfd
      - /dev/dri
