name: Publish Image to GHCR
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"
  schedule:
    - cron: "0 0 * * 0"

env:
  IMAGE_NAME: whisper-server-vulkan
  MODEL: ggml-large-v3-turbo-q8_0.bin

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install huggingface-cli
        uses: BSFishy/pip-action@v1
        with:
          packages: huggingface_hub[cli]

      - name: Download GGUF
        run: |
          huggingface-cli download ggerganov/whisper.cpp --include "${{ env.MODEL }}" --local-dir .

      - name: Checksum GGUF
        run: |
          sha256sum ${{ env.MODEL }}

      - name: Build Image with Buildah
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ./Containerfile
          image: ${{ env.IMAGE_NAME }}
          build-args: |
            MODEL=${{ env.MODEL }}
          labels: |
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository }}/main/README.md
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=${{ env.MODEL }}
            org.opencontainers.image.source=https://huggingface.co/ggerganov/whisper.cpp

      - name: Push Image to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
