name: Publish Image to GHCR
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"
  schedule:
    - cron: "0 0 * * 0"

env:
  IMAGE_NAME: whisper-server-vulkan
  MODEL: ggml-large-v3-turbo-q8_0.bin

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install huggingface-cli
        uses: BSFishy/pip-action@v1
        with:
          packages: huggingface_hub[cli]

      - name: Download GGUF
        run: |
          huggingface-cli download ggerganov/whisper.cpp --include "${{ env.MODEL }}" --local-dir .

      - name: Build Image with Buildah
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ./Containerfile
          image: ${{ env.IMAGE_NAME }}
          labels: |
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository }}/main/README.md
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=${{ env.MODEL }}
            org.opencontainers.image.source=https://huggingface.co/ggerganov/whisper.cpp

      - name: Start server
        uses: mathiasvr/command-output@v2.0.0
        id: container
        with:
          run: |
            podman run -d -p 8001:8080 localhost/${{ env.IMAGE_NAME }}

      - name: Wait for server to load
        uses: juliangruber/sleep-action@v2.0.0
        with:
          time: 15s

      - name: Download JFK audio
        run: |
          curl -Lo jfk.mp3 https://github.com/ggml-org/whisper.cpp/raw/refs/heads/master/samples/jfk.mp3

      - name: Run inference
        uses: mathiasvr/command-output@v2.0.0
        id: api
        with:
          run: |
            curl -v 127.0.0.1:8001/inference \
            -H "Content-Type: multipart/form-data" \
            -F file="@jfk.mp3" \
            -F temperature="0.0" \
            -F temperature_inc="0.2" \
            -F response_format="text"

      - name: Print server logs
        run: |
          podman logs ${{ steps.container.outputs.stdout }}

      - name: Push Image to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
